---
Period: 60
MonitoringType: "Basic"
PrometheusPort: 2001
AWSAccessKey: ""
AWSSecretKey: ""
DBInstances:

  - DBInstanceIdentifier: "dev-applayer-mariadb"
    Region: "us-east-1"
    DBEngine: "maria"
    AvailabilityZone: "us-east-1b"