---
Period: 60
MonitoringType: "Basic"
PrometheusPort: 2001
DBInstances:

  - DBInstanceIdentifier: ""
    Region: "us-east-1"
    AWSAccessKey: ""
    AWSSecretKey: ""
    DBEngine: "maria"
    AvailabilityZone: "us-east-1a"